# Generated by Django 5.0.7 on 2024-09-16 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('attachment_id', models.AutoField(primary_key=True, serialize=False)),
                ('attachment_name', models.CharField(max_length=30)),
                ('attachment_type', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('weapon_id', models.AutoField(primary_key=True, serialize=False)),
                ('weapon_name', models.CharField(max_length=30)),
                ('weapon_type', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='AttachmentType',
            fields=[
                ('attachment_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('attachment_type_name', models.CharField(max_length=30)),
                ('attachment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='class_upvote.attachment')),
            ],
        ),
        migrations.AddField(
            model_name='attachment',
            name='weapon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='class_upvote.weapon'),
        ),
    ]
