# Generated by Django 5.0.7 on 2024-09-22 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_upvote', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_name', models.CharField(max_length=30)),
                ('main_weapon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='class_upvote.weapon')),
            ],
        ),
    ]
