# Generated by Django 5.0.7 on 2024-09-22 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_upvote', '0002_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='attachment1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='post_attachment1', to='class_upvote.attachment'),
        ),
        migrations.AddField(
            model_name='post',
            name='attachment2',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='post_attachment2', to='class_upvote.attachment'),
        ),
        migrations.AddField(
            model_name='post',
            name='attachment3',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='post_attachment3', to='class_upvote.attachment'),
        ),
        migrations.AddField(
            model_name='post',
            name='attachment4',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='post_attachment4', to='class_upvote.attachment'),
        ),
        migrations.AddField(
            model_name='post',
            name='attachment5',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='post_attachment5', to='class_upvote.attachment'),
        ),
    ]
