# Generated by Django 5.0.7 on 2024-10-05 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_upvote', '0003_alter_vote_vote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='post_voted',
        ),
        migrations.AddField(
            model_name='post',
            name='vote',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='class_upvote.vote'),
            preserve_default=False,
        ),
    ]
