# Generated by Django 5.0.7 on 2024-10-05 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_upvote', '0004_remove_vote_post_voted_post_vote'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostsVoted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_vote', models.BooleanField()),
                ('vote', models.CharField(choices=[('upvote', 'UpVote'), ('downvote', 'DownVote')], max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='vote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='class_upvote.postsvoted'),
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
