# Generated by Django 5.0.7 on 2024-10-05 20:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_upvote', '0005_postsvoted_alter_post_vote_delete_vote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='vote',
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.CharField(choices=[('upvote', 'UpVote'), ('downvote', 'DownVote')], max_length=10)),
                ('post_voted', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='class_upvote.post')),
                ('voted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='PostsVoted',
        ),
    ]
