# Generated by Django 5.1.1 on 2024-10-10 15:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_upvote', '0006_remove_post_vote_vote_delete_postsvoted'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='created_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Time Created'),
        ),
    ]
