# Generated by Django 5.1.1 on 2024-10-10 15:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_upvote', '0008_alter_post_created_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_time',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Time created'),
        ),
    ]
